apiVersion: apps/v1
kind: Deployment
metadata:
  name: sspl
  labels:
    app: sspl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: centos-app
  template:
    metadata:
      labels:
        app: centos-app
    spec:
      hostNetwork: true
      containers:
      - name: centos-container
        image: centos:centos7.8.2003
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /var/run/dbus/system_bus_socket
            name: dbus-socket
          - mountPath: /dev/sda1
            name: sda1
          - mountPath: /sys/block
            name: sys-block
          - mountPath: /dev/ipmi0
            name: ipmi
      volumes:
      - name: dbus-socket
        hostPath:
          path: /var/run/dbus/system_bus_socket
          type: Socket
      - name: sda1
        hostPath:
          path: /dev/sda1
          type: BlockDevice
      - name: ipmi
        hostPath:
          path: /dev/ipmi0
          type: CharDevice
       
